### ISSUE TITLE
It can't support GitHub Enterprise server 

### ISSUE THREAD

**Issue by trend-yafang-qiu** [ActionsDesk/report-action-usage#41]
### Is your feature request related to a problem? Please describe.

We used GitHub enterprise which host by ourself 
### Describe the solution you'd like

This action can support GHEE
### Describe alternatives you've considered

the same with cloud

**Comment by stoe** [comment]
@trend-yafang-qiu, happy for any PR if you want to give it a try adding a `ghe_host` config.

**Comment by trend-yafang-qiu** [comment]
Hi @stoe 
Since I am not familiar with the development language, it is difficult to complete this feature. I wonder if enhance will be in your backlog. Looking forward to your reply

**Comment by stoe** [comment]
Hi @trend-yafang-qiu, currently no plans.
This issue now being labeled with https://github.com/ActionsDesk/report-action-usage/labels/enhancement as a feature request, it's now on the backlog.

**Comment by stoe** [comment]
Closing as this project is now unmaintained.
